### ISSUE TITLE
Quest chain in II - Getting on Up is blocked

### ISSUE THREAD

**Issue by ArrienRK2** [FTBTeam/FTB-Modpack-Issues#4948]
### Modpack

FTB Skies Expert

### Modpack version

1.4.1

### Describe the bug

Every since 1.3.3 when I reached this quest stage, my quests have shown up as 100% with a grey checkmark, but no green checkmark. I have 5x checked dependencies, and all of them are complete. 

### Steps to reproduce

No one else on my server has complained of this, so I'm not sure there's a good repro. 
I don't remember which order I completed the dependencies unfortunately. 

![failed dependencies](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/26645068/8bec5222-e5c7-413f-b672-7da2a515f9b1)

### Expected behaviour

I would expect for the quests to complete.

**Comment by kmadstarh** [comment]
You're missing a dependency which isn't immediately apparent, the Nasa Workbench quest requires completion of the Simple Machine Frame quest, which you haven't cleared yet.

**Comment by ArrienRK2** [comment]
Yes, but you see that there is also a grey check next to the simple machine frame quest, because I've already got 100% on that too, and it also won't complete. I've included a screenshot that shows that the Simple Machine Quest lists as 100%, and has a grey check, but doesn't have the green check on the item, although if you look very carefully, I have 2 simple machine frames in my hotbar.
![simple machine uncompleted](https://github.com/FTBTeam/FTB-Modpack-Issues/assets/26645068/a5c35edd-7133-4ec0-a133-6e900f98529c)


Weirdly, I just completed a quest in the brand new Pneumaticraft line and it went about 15 minutes, scrolling through completions of all the quests in "II - Getting on Up" that I had already completed and had green checks, but it still didn't give me completion on the ones with grey checks. It did give me completion pop-ups over and over for the same quests. Logging out and back in stopped the spam.

**Comment by ArtpokeBr** [comment]
If you have acess to OP Privileges, enter on edit mode, refresh the progress and resubmitt, this should do the trick.

Its a weird issue with FTB Quests, by doing this it should work.

**Comment by ArtpokeBr** [comment]
Well, there is no solution really then.... there is an updated task, not quest, somewhere you need to find and address, likely in another chapter. Or if you had OP you could do the editing mode thing... Unfortunatly this is a current issue with FTB Quests that hopefully should be fixed in the future.

Unfortunatly you're the one that needs to get into editing mode, so no mod can fix this for you directly =/

**Comment by krisavi** [comment]
> Yes, but you see that there is also a grey check next to the simple machine frame quest, because I've already got 100% on that too, and it also won't complete. I've included a screenshot that shows that the Simple Machine Quest lists as 100%, and has a grey check, but doesn't have the green check on the item, although if you look very carefully, I have 2 simple machine frames in my hotbar. ![simple machine uncompleted](https://private-user-images.githubusercontent.com/26645068/312237185-a5c35edd-7133-4ec0-a133-6e900f98529c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MTM2OTEsIm5iZiI6MTcxMDQxMzM5MSwicGF0aCI6Ii8yNjY0NTA2OC8zMTIyMzcxODUtYTVjMzVlZGQtNzEzMy00ZWMwLWExMzMtNmU5MDBmOTg1MjljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDEwNDk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmMzYyYWRjZjY0NGE0Y2UxNWM5Y2RjNzk4NjNhMThkNmI0ZTc2ZGYwMmQ0MDk4MDhhZWJjN2Q5MWU2ODM4ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DpuzaS7GaPcpqRx_vZdQTZrU6RVx6Htk-96YRKMTy1o)
> 
> Weirdly, I just completed a quest in the brand new Pneumaticraft line and it went about 15 minutes, scrolling through completions of all the quests in "II - Getting on Up" that I had already completed and had green checks, but it still didn't give me completion on the ones with grey checks. It did give me completion pop-ups over and over for the same quests. Logging out and back in stopped the spam.

Does this quest have any dependencies? You can check from the arrow < in the upper corner. Maybe one of those is not completed yet.

**Comment by kmadstarh** [comment]
> Does this quest have any dependencies? You can check from the arrow < in the upper corner. Maybe one of those is not completed yet.

To add on to this, it's possible one of those dependencies is missing a dependency somewhere in a long chain of dependencies. I know recent updates added dependencies to previously completed quests, making them both grayed out and complete at the same time. It's possible this is preventing the simple machine frames quest from completing properly.

**Comment by ArrienRK2** [comment]
Thanks for all the suggestions, I really appreciate it. I've crawled through the possible added dependencies, and you may be right because when I completed some of the new "Airbending" quest chain, it did update some other quests, but still not this one. I'll just keep trying to complete more and see if it triggers these. I was mostly raising the issue in case there was something in the quest dependency chain that you needed to fix, but if it's just something in FTBQuests that I got unlucky to hit, that's fine.
