### ISSUE TITLE
Steves Cart External Distributor loses all its settings on a relog-in.

### ISSUE THREAD

**Issue by WebDragon** [FTBTeam/FTB-Modpack-Issues#6020]
### Modpack

FTB NeoTech

### Modpack version

1.7.0

### Launcher

FTB App

### Has the pack been modified

No

### Describe the bug

External Distributor settings are  lost on logout 

### Steps to reproduce

1. set up Steves Carts cargo manager with external distributor on top, and configure both
2. ensure set up is working by observing transfer of logs sticks and saplings from cart to external drawers 
3. log out (quit to title screen) 
4. log in (reload your save)
5. observe that External Distributor has lost its settings 

### Expected behaviour

settings are retained so one does not have to tediously go reset the tree farm every time you join your game

### Screenshots

![Screenshot 2024-10-27 183254](https://github.com/user-attachments/assets/0d904fac-8f8c-4ccb-9149-62044555e05f)
![Screenshot 2024-10-27 183242](https://github.com/user-attachments/assets/9e0a3dc4-e549-4c31-bb84-f4863f87332e)
![Screenshot 2024-10-27 183020](https://github.com/user-attachments/assets/9bc8d544-5dc1-4072-830f-5fc9378ea9da)

![2024-10-27_18 33 06](https://github.com/user-attachments/assets/8eda243e-5d40-48a6-850c-5e06c1faad02)
![2024-10-27_18 33 16](https://github.com/user-attachments/assets/2177eb01-59b9-4f26-8285-db1a9927c6be)

**Comment by WebDragon** [comment]
forgot cargo manager screenshot 
![2024-10-27_18 40 10](https://github.com/user-attachments/assets/e5024ed4-25cf-4046-a4ba-10b6539d8794)

**Comment by WebDragon** [comment]
mod dev closed issue against newer version of minecraft -- left inquiry as to whether said patch could be backported to this version of minecraft so the ftb modpack could have the fix. awaiting dev response.

**Comment by ArtpokeBr** [comment]
Yeah.. this issue is still a thing and there's currently no Update about it...

**Comment by sTiKyt** [comment]
Still no fix

How am I supposed to automate tree farming early-game without it? Can anyone help?

**Comment by WebDragon** [comment]
> Still no fix
> 
> How am I supposed to automate tree farming early-game without it? Can anyone help?

For the time being, I put up a sign in my base to remind me, every time I log into it, to go re-set the settings, and set up a pair of JustDireThings Drops Teleporters (configured to teleport me between them instead) to facilitate that. Since my configuration only requires me to remember two settings that need to be replaced, it's fairly straightforward

**Comment by WebDragon** [comment]
Mod dev reopened the issue for a backport to 1.20.4 and it has been reported as fixed in dev  - hopefully seeing a release soon that can get squeezed into a NeoTech update in the near future

**Comment by ArtpokeBr** [comment]
Just Updated Steve's Carts in Dev, please confirm to us if this got fixed after the pack update :)

**Comment by WebDragon** [comment]
> Just Updated Steve's Carts in Dev, please confirm to us if this got fixed after the pack update :)

just checking - there's a 1.2.8 release from Jan 9th but that's the same day the commit and version bump was made in dev to 1.2.9 so the version with the fix may not be released yet --but I'll be the first to admit I am not 100% sure, however the version bump to 1.2.8 was made 3 weeks ago back in december. https://github.com/CreeperHost/StevesCarts2/commits/1.20.4/ Am I reading this right?

**Comment by faizjamil** [comment]
Just tested Steve's Carts 1.2.8 for 1.20.4 in a creative world, bug is still there. Can anyone confirm this?

**Comment by WebDragon** [comment]
The official release has been published https://www.curseforge.com/minecraft/mc-mods/creeperhost-presents-steves-carts/files/all?page=1&pageSize=20 as 1.20.4-1.2.10 as per https://github.com/CreeperHost/StevesCarts2/issues/45#issuecomment-2624478762
