### ISSUE TITLE
Something in my world crashes 1.4.0

### ISSUE THREAD

**Issue by SudzBud** [FTBTeam/FTB-Modpack-Issues#6107]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.4.0

### Launcher

FTB App

### Has the pack been modified

No

### Log Files

[crash-2024-11-07_10.17.12-server.txt](https://github.com/user-attachments/files/17663886/crash-2024-11-07_10.17.12-server.txt)

### Describe the bug

Crash on startup after upgrade to 1.4.0.

downgrade back to 1.3.0 and loads fine

### Steps to reproduce

I'm guessing you'd have to have my world save to reproduce.

### Expected behaviour

Upgrade and world just loads

**Comment by lattaai3** [comment]
Hello, I tried to fix the issue

This is what I did:

Updated the .github/ISSUE_TEMPLATE/bug_reports.yml file to include 'FTB Presents Direwolf20 1.21' in the modpack options and made minor improvements to the template.

I also created pull request: https://github.com/FTBTeam/FTB-Modpack-Issues/pull/6108


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

**Comment by shank3001** [comment]
Expierenced the same issue. Stuck at 8% on world spawn. Keeps indicateing waiting on world statisitics.
[2024-11-07-1.log.gz](https://github.com/user-attachments/files/17667852/2024-11-07-1.log.gz)

**Comment by Gaz492** [comment]
As a temporary fix until we get this resolved, try disabling the mod `moonrise`
[](!skip)

**Comment by T-Blade** [comment]
Disabling moonrise seemed to fix the crash for me.
i can also tell on a fresh new world, placing the minecolonies town hall instantly crashed my game before with Moonrise enabled. (if that is any help)

- Minecolonies issues: Rallying banner still does not do anything. Postbox and stash do not get removed from inventory on placement, spawns world item, but not removed after placement from inventory.

**Comment by Prossy22** [comment]
Thankyou Gaz, that also worked for me too

**Comment by shank3001** [comment]
Same here. . .Thanks!!!

**Comment by Gaz492** [comment]
This is fixed in the latest version of the modpack as we have removed moonrise
