### ISSUE TITLE
Server crashes every five minutes after update

### ISSUE THREAD

**Issue by jjjworley** [FTBTeam/FTB-Modpack-Issues#6589]
### Modpack

FTB Evolution

### Modpack version

1.7.0

### Launcher

FTB App

### Has the pack been modified

Yes

### Log Files

https://pastebin.com/h8KHfRxH

### Describe the bug

The server crashes and leaves a crash log. I have included the most recent crash log.

### Steps to reproduce

Play the game for 5 minutes and the server crashes. The game worked well for about a day after the update then all of a sudden keeps crashing now

### Expected behaviour

Not to crash.

**Comment by ImHer0** [comment]
The server seems to be timing out due to a server tick reaching the limit.

If the server has somewhat stable tps but timeouts and crashes you can change this in server.properties by setting `max-tick-time=-1`

alternatively after doing that you can use the spark profiler **In Console** by doing `/spark profiler start` and then `/spark profiler stop` and checking out what is causing your ticks to go that high. I had this issue on this pack previously where there were 190K items on the floor when there weren't any on the chunks causing my server to lag extensively.

**Comment by jjjworley** [comment]
Miraculously the server started working fine after about 10 crashes. Thank you for looking into this. I ran /spark profiler start and stop but I don't know where to find the results. It seems the last update did a lot of damage to the game. The Mekanism ore generator and lasers crash the game when you attempt to access the gui, the Mekanism fission reactor is barely putting out any steam, lots of odd changes in other mods such as EnderIO sag mill no longer automatically inputting or outputting from chests, Modern Industrialization crude oil no longer creating synthetic oil in the steam blast furnace and lots of other odds and end changes.

**Comment by ImHer0** [comment]
what I figured also is that with servers it's all really messy for the most random reasons and most of the time the fix will be so random you don't even know how it fixed leaving you more confused but I guess just try to use spark and if needed and provide the link in a post to better help with that.

And yes, there is currently a client crash with Mekanism Lasers and Mekanism Turrets whenever opening their GUIs, this has been fixed since yesterday.

> [New update has been released (MekanismLasers-1.12.1-1.1.10) when curseforge approves it you can just update the mod to that version and it should work as expected!](https://github.com/Ominox0/mekanism_lasers/issues/15)

I haven't exactly experienced the fission reactor having issues but if you believe this is a bug probably send a bug report on their github to address that.

same thing with the sag mill and steam blast furnace.

**Comment by jjjworley** [comment]
I updated Mekanism lasers and it resolved the issue with the ore generator, but the laser turrets still crash the game when trying to access their gui. Thank you for your help with this! :)

**Comment by ArtpokeBr** [comment]
Had to downgrade Mekanism, but both the Crash with Mekanism Lasers and Mekanism Turrets should be sorted now.

**Comment by Ominox0** [comment]
> I updated Mekanism lasers and it resolved the issue with the ore generator, but the laser turrets still crash the game when trying to access their gui. Thank you for your help with this! :)

elo, I got pinged XD, yeah so I updated my mod few days ago <3
