### ISSUE TITLE
When I connected to Tesseract using Orietech's pipe, the game crashed

### ISSUE THREAD

**Issue by RIsiSky** [FTBTeam/FTB-Modpack-Issues#7264]
### Modpack

FTB OceanBlock 2

### Modpack version

1.3.2

### Launcher

Other...

### Has the pack been modified

No

### Log Files

无

### Describe the bug

This problem occurs when Fabric combines the transport API through the Forgified Fabric API with the NeoForge project handler API.The Forgified Fabric API team solved the problem yesterday and released the latest version of the 2.0.24 mod. However, FTB OceanBlock2 is not updated in the latest version 1.4.1, and still uses the FFAPI of 2.0.23.

### Steps to reproduce

1.Place two Tesseract squares
2.Create a channel
3.Input fluid using Orietech's pipe (I used water) into a Tesseract and activate the channel
4.Output fluid from another Tesseract using Orietech's pipe (I used water) and activate a channel in another Tesseract
5.Congrats! The game crashed.

### Expected behaviour

The game crashed.

### Screenshots

<img width="462" alt="Image" src="https://github.com/user-attachments/assets/6c562653-258a-46cc-9e77-ff6cba56922c" />

**Comment by RIsiSky** [comment]
I'm sure I downloaded the latest version of the integration package, 1.4.2, and the FFAPI in it was updated to 2.0.24. But the above action still crashes the game. I looked at the file for FFAPI version 2.0.24 and the fabric-transfer-API version is 628bf5e919. But the error version of the game launcher is 719f32719. Does this mean that the new FFAPI is not being used and is causing an error?

**Comment by Gaz492** [comment]
Are you able to upload a full crash report for us so we can take a look?

**Comment by RIsiSky** [comment]
> Are you able to upload a full crash report for us so we can take a look?

Sure, I re-downloaded the latest version of integration Package 1.4.2 to make sure nothing changed.I uploaded the report file that just crashed the game

[crash-2025-03-10_18.50.30-server.txt](https://github.com/user-attachments/files/19160963/crash-2025-03-10_18.50.30-server.txt)

**Comment by Gaz492** [comment]
Thanks, could you try following the guide below? It should fix the issue you are running into
https://docs.feed-the-beast.com/docs/support/Troubleshooting/ticking-entities/#packs-running-neoforge-1204-and-newer

**Comment by RIsiSky** [comment]
> Thanks, could you try following the guide below? It should fix the issue you are running into https://docs.feed-the-beast.com/docs/support/Troubleshooting/ticking-entities/#packs-running-neoforge-1204-and-newer

I did this before, and the game didn't crash, but Tesseract lost its effect. It appears that NeoForge deleted Tesseract's connection to the fluid pipeline when it discovered that it was about to collapse. It doesn't solve the problem, per se.FFAPI fixed this issue in the last update, but it doesn't seem to be working in the integration package. [https://github.com/Sinytra/ForgifiedFabricAPI/pull/201](url)

**Comment by DinnerBeef** [comment]
This issue should have been fixed in `1.4.2`! Please reopen this issue if you are still having problems.

**Comment by RIsiSky** [comment]
> This issue should have been fixed in `1.4.2`! Please reopen this issue if you are still having problems.

I'm sorry if I wasn't very clear. It is because I still have this problem after downloading the 1.4.2 integration package that I bring it up here. In other words, 1.4.2 doesn't actually fix the problem. The latest version of FFAPI has modified the fabric-transfer-api to fix the above issues, and the revised version is 5.4.1+628bf5e919. You can see it in the compression software.

![Image](https://github.com/user-attachments/assets/39e067fe-92d2-4672-9c5c-1a5292e9d758)
However, when I went into the 1.4.2 integration package, I found that the version of fabric-transfer-api was still stuck at 5.4.1+d719f32719. That is to say, the mods loaded in the game are actually old mods, and there are no new mods loaded that have fixed the problem.

![Image](https://github.com/user-attachments/assets/47f19886-df23-4936-a79e-efc097ff6b26)
So that's what I think is causing the problem. As far as my play is concerned, this problem has not been solved. By the way, I don't have permission to reopen it.
:)

**Comment by DinnerBeef** [comment]
Ahh, it seems. Seem like I missed read the version when looking at the mod list.

**Comment by RIsiSky** [comment]
@DinnerBeef 
I'm sorry to bother you.
 I downloaded 1.21.1 with Neoforge and added only the latest version of FFAPI to it. In the game, you can see that FFAPI loads normally with fabric-transfer-api-v1-5.4.1+628bf5e919. So now I'm pretty sure the problem is probably in modpack and not FFAPI. Maybe you could check the modpack Settings? 
Thank you! :)
