### ISSUE TITLE
Metal dusts not smelting to ores, no recipe in JEI

### ISSUE THREAD

**Issue by CassantheMum** [FTBTeam/FTB-Modpack-Issues#7811]
### Modpack

FTB Presents Direwolf20 1.21

### Modpack version

1.14.0

### Launcher

FTB App

### Has the pack been modified

Yes

### Log Files

[console.log](https://github.com/user-attachments/files/20369257/console.log)

[debug.log](https://github.com/user-attachments/files/20369263/debug.log)

### Describe the bug

I can convert ores to dusts using the Mekanism Enrichment Chamber, but I cannot convert the dust to ingots in any machine. There is no recipe in JEI to convert dusts to ingots. This includes steel - I can process the iron twice in the metallurgic infuser, but the resulting dust cannot be converted to steel. The ingots are in JEI, but there is no way to convert. I can convert ores to ingots using the Minecraft furnaces. I have not tried using the Mekanism purification chamber set up yet. I've never had this issue before in this or any other pack. I have recently updated the pack to the latest version. 

Fairly new save of a few days ago.

### Steps to reproduce

1. Process ores in the Mekanism Enrichment Chamber to dust
2. Try to smelt dust in the Smelter, Furnace, or Blast Furnace. 

### Expected behaviour

I expect to be able to process dust to ingots 

### Screenshots

![Image](https://github.com/user-attachments/assets/f7d71569-545f-4a37-848d-f64948bee4aa)

![Image](https://github.com/user-attachments/assets/e36efbac-fe3e-4d90-ad62-846dd96e7a8c)

![Image](https://github.com/user-attachments/assets/1eeefcc9-715c-491a-ab1d-fbde2181e50b)

### Additional information

Added MVS - Moog's Voyager Structures and FTB Ultimine

**Comment by DietmarKrause** [comment]
same here, cannot make steel ingots out of steel dust any more

**Comment by DaikonStew** [comment]
I've just found out the same. Huge problem

**Comment by Jim3535** [comment]
Same problem here. It's going to really derail using mekanism since we can't make steel.

**Comment by swpistol** [comment]
I'm testing for Both FTB launcher and curseforge My modpack has not been modified and it wont let me turn dust into ingots on either client.

**Comment by ArtpokeBr** [comment]
This should be fixed in Dev, soon to be released in 1.14.1

**Comment by ProfessorTee** [comment]
hey guys a probably temporary work around for this is to create a new kubejs file* with the following lines:

go to:
\ftb presents direwolf20 121\kubejs\server_scripts\02_mod_specific
create ,js file or copy paste an existing file and replace its content with:
(preferably rename it to something like "18_temp_fix.js" <3
```
ServerEvents.recipes(event => {
  let dustToIngot = [
    ['mekanism:dust_iron', 'minecraft:iron_ingot'],
    ['mekanism:dust_gold', 'minecraft:gold_ingot'],
    ['mekanism:dust_copper', 'minecraft:copper_ingot'],
    ['mekanism:dust_steel', 'mekanism:ingot_steel'] 
  ];

  dustToIngot.forEach(([input, output]) => {

    event.smelting(output, input).xp(0.7).cookingTime(200);
    

    event.blasting(output, input).xp(0.7).cookingTime(100);
  });
}};
```

**Comment by CassantheMum** [comment]
Hey there,  @ProfessorTee 

I did this with the rename of a copy of one of the files and copy/pasted your text there and it didn't work. I don't know how to program or code so I don't know what to look for. Any ideas? Thank you!

Cass

**Comment by CassantheMum** [comment]
Oh! I went into the Removal file in that server events folder and removed the oritech entries for ingots from dust. It works!

**Comment by DietmarKrause** [comment]
no not fixed. Steel dust cannot be smelted, this has not been fixed,

**Comment by n0eL1405** [comment]
Despite being fixed in new version, here is a fixed version of @ProfessorTee 's script (including steel dust @DietmarKrause):
```
ServerEvents.recipes(event => {
  let dustToIngot = [
    ['mekanism:dust_iron', 'minecraft:iron_ingot'],
    ['mekanism:dust_gold', 'minecraft:gold_ingot'],
    ['mekanism:dust_copper', 'minecraft:copper_ingot'],
    ['mekanism:dust_steel', 'mekanism:ingot_steel'] 
  ];

  dustToIngot.forEach(([input, output]) => {

    event.smelting(output, input).xp(0.7).cookingTime(200);
    

    event.blasting(output, input).xp(0.7).cookingTime(100);
  });
});
```

**Comment by CassantheMum** [comment]
Oh, yeah. That's right. Steel dust doesn't work. It did earlier with my removing stuff fix. Not with the new update.

**Comment by CassantheMum** [comment]
Delete in the steel dust/ingot file as before. Works.
