### ISSUE TITLE
[Bug]: Server crashes randomly from tick taking too long. Seems to be mob AI problem.

### ISSUE THREAD

**Issue by legitswitch** [FTBTeam/FTB-Modpack-Issues#87]
### Modpack

FTB OceanBlock

### Modpack version

1.2

### Log Files

https://hastebin.com/ibamuficim.properties

### Describe the bug

I've had this same crash several times. The server watchdog will stop the server due to a tick taking over 60 seconds. It seems to have something to do with mobs and their AI. Looks like Roadrunner causes a crash when a zombie attacks something underwater? 

The crash log mentions various mods' mixins, including:
Roadrunner
Aquafied
BetterDiving
ImmersiveEngineering
WYML
BetterEndForge
FTBJanitor
KubeJS
Botania

### Steps to reproduce

Not sure how to replicate it easily yet. I'll test spawning zombies and other mobs underwater and then post an update.

### Expected behaviour

Server shouldn't crash

**Comment by Raidobw2** [comment]
If you set `max-tick-time=-1` in server.properties that should fix it by disabling the watchdog. Is your server dedicated or rented on an online host, using a vCPU?

**Comment by legitswitch** [comment]
Dedicated server on my home PC, no vCPU

Crash happened again:
https://hastebin.com/ucafoqagur.rb

**Comment by legitswitch** [comment]
Anywhere from 1 to 6 players. There is no common player in the crashes. I looked through the dozen crashes like this I've had in the past two days.

Something I noticed in the two crash reports I posted if it helps:
Crash 1: Has net.minecraft.entity.ai.goal.MeleeAttackGoal
Crash 2: Has net.minecraft.entity.ai.goal.RangedAttackGoal

I just removed RoadRunner instead of making do with a possible two minute lag spike from the tick. I haven't tested downgrading RoadRunner yet. Haven't had this crash in 18 hours so far after removing it.

**Comment by legitswitch** [comment]
Setting max-tick to -1 didn't fix it for me. One tick was at 5 minutes before I stopped it manually. Everyone couldn't join due to a timeout error.

I got crashes relating to entity AI even after removing roadrunner: https://hastebin.com/nikovufopo.sql
Crash after removing only wyml mod (why you make lag): https://hastebin.com/ugabuxihiy.rb

The last lag spike from this was about 37 seconds at a player's underwater base. Didn't see anything unusual aside from a drowned zombie with a fishing hook. It had crashed twice right before this when the player joined.

**Comment by Raidobw2** [comment]
I read the Minecraft wiki a bit, tried to get info about ticks, so here it is:

```
In Java Edition, in each game loop the following actions are processed in order:

  Each dimension is ticked in order of overworld, the nether, and the end. For each dimension:

      The time is sent to the client
      The world border is updated
      Weather logic
      Player sleeping logic
      If this dimension is overworld:
            The game-time and day-time increase
            Scheduled functions are executed
      For each loaded chunk:
            Chunk info is sent to the client
            Chunk tick logic
      Phantoms, pillagers, cats, and zombie sieges will try to spawn
      Entity changes are sent to the client
      Chunks try to unload
      Scheduled ticks are processed
            Scheduled block ticks
            Scheduled fluid ticks
      Raid logic
      Wandering traders try to spawn
      Block events are processed
      Entities are processed
      Block entities are processed
```
No idea is this is pertinent, maybe Sunekaer will know a thing or two that i don't. Here goes:

There's a lot of water in OceanBlock. I guess that shouldn't cause a problem, but notice "Scheduled fluid ticks" is placed before the processing of "Entities are processed" according to that list (is this info trustable from the wiki?).

Everytime the server crashes for legitswitch, it's a different mob. So probably the watchdog crashes at the end of that processing, and something in-between adds a metric ton of lag for some reason.

"Block entities are processed" is at the end, and i think that would be minecraft campfires? Anyways, this might link to the following info from the 4 crashes from legitswitch:


1 ----- `Level stats: ResourceKey[minecraft:dimension / minecraft:overworld]: players: 1, entities: 1291 [minecraft:wither_skull:914,minecraft:item:74,minecraft:rabbit:39,botania:spark:32,minecraft:pig:29], block_entities: 4549 [minecraft:campfire:498,mekanism:basic_universal_cable:327,minecraft:chest:261,pipez:item_pipe:214,cb_multipart:saved_multipart:213], block_ticks: 3749, fluid_ticks: 154030, chunk_source: ServerChunkCache: 32052`

2 ----- `Level stats: ResourceKey[minecraft:dimension / minecraft:overworld]: players: 2, entities: 1492 [minecraft:wither_skull:916,minecraft:item:235,minecraft:tropical_fish:42,minecraft:rabbit:41,botania:spark:32], block_entities: 4306 [minecraft:campfire:1036,cb_multipart:saved_multipart:389,minecraft:chest:258,mekanism:basic_universal_cable:147,botanypots:botany_pot:130], block_ticks: 22421, fluid_ticks: 897178, chunk_source: ServerChunkCache: 26942`

3 ----- `Level stats: ResourceKey[minecraft:dimension / minecraft:overworld]: players: 3, entities: 180 [minecraft:tropical_fish:61,botania:spark:22,minecraft:squid:18,minecraft:rabbit:11,minecraft:chicken:10], block_entities: 2503 [minecraft:campfire:909,cb_multipart:saved_multipart:223,mekanism:basic_universal_cable:140,minecraft:chest:130,minecraft:mob_spawner:70], block_ticks: 7863, fluid_ticks: 312879, chunk_source: ServerChunkCache: 14739`

4 ----- `Level stats: ResourceKey[minecraft:dimension / minecraft:overworld]: players: 2, entities: 105 [minecraft:tropical_fish:43,minecraft:squid:11,minecraft:rabbit:10,minecraft:pig:8,minecraft:chicken:6], block_entities: 1701 [minecraft:campfire:611,cb_multipart:saved_multipart:146,mekanism:basic_universal_cable:140,minecraft:chest:116,mekanism:basic_mechanical_pipe:61], block_ticks: 6316, fluid_ticks: 259754, chunk_source: ServerChunkCache: 12332`

The fluid ticks are massive and especially at the second one, where it almost hit a million. Apparently these ticks are for the flow of water, but i'm honestly not sure -- speculation from seeing this online and guessing about it too.

There's a guy who casually dropped about one thousands wither skulls from the 1st and 2nd crash but i don't think that'd be a problem, as we see from the 3rd and 4th crash. Mek cables should not cause an issue unless they're all congested, we can compare with the Spark profile from gdharron and they don't seem to cause a log of lag.

The number of campfires is also high but that's normal from all the rafts, plus, from earlier i mentioned that's technically processed after the Entities, so i don't think they got processed yet in those crashes (if this info was trustable).

Anyway that's just an observation i wanted to bring to Sunekaer's eye, he'll know if it's pertinent.

Might dig again later when i get more time.

P.S.: Understood from the Spark report that WYML regulates mob spawn checks, so that should probably stay within servers, it technically reduces lag from spawn checks. If i understood correctly!

**Comment by gdharron** [comment]
Sorry this is getting abit long but just wanted to throw this up here for you guys to glance at, it's got the last 4 hours of my server on it looking at ticks over 100 ms 

https://spark.lucko.me/oH54O9HoAO

**Comment by gdharron** [comment]
> Could you try and go to wyml.json in config folder and change ALLOW_PAUSE_CLAIMED and ALLOW_PAUSE_FORCED to true and see if that reduces the tick lag when there is that many people

had this setting enabled since you posted it and server is still crashing at a certain players island. see spark report below.

**Comment by ronmaster9000** [comment]
so i happened to find the exact source i think... i set gamemode to peaceful which should despawn all hostile mobs but i had noticed one drowned zombie in the server with crashustilities, tried to clear the zombie and it would not clear. i teleported to the drowned and there was an obsidian boat at the exact location i teleported to... so it could be the fact that the drowned might be inside the obsidian boat on the bottom of the ocean causing the crash...

**Comment by gdharron** [comment]
It definitely has something to do with the drowned cause the massive lag, sub-issue is maybe the obsidian boats but after having a crash every 30 mins all morning I set it to peaceful and everything was fine and I removed the extra boats. I just went back to normal and it was good then all of a sudden I had 2 TPS, I used crash utilities to remove the 7x drowned and then back to 20 TPS.
