### ISSUE TITLE
Missing the oritech:magnetic_coil recipe

### ISSUE THREAD

**Issue by Odegaard** [FTBTeam/FTB-Modpack-Issues#8734]
### Modpack

FTB Skies 2

### Modpack version

1.5.2

### Launcher

FTB App

### Describe the bug

Can't make the oritech:magnetic_coil due to missing stuff

<img width="673" height="575" alt="Image" src="https://github.com/user-attachments/assets/338dca7d-f63c-4766-8244-2b9d381b4884" />

<img width="1015" height="406" alt="Image" src="https://github.com/user-attachments/assets/547eb181-9dad-4200-ad72-a4fcc3bccb4f" />

### Steps to reproduce

1. search JEI for "magnetic coil" 
2. Check how its suppose to be made

### Expected behaviour

Being able to see the block

### Has the pack been modified

Yes

**Comment by sitnoveter** [comment]
make sure you are playing on the version you have said you are.
that issue has been fixed on 1.5.2

<img width="666" height="504" alt="Image" src="https://github.com/user-attachments/assets/b6408a64-d95f-4fe7-b970-3a9fd29acc95" />

<img width="667" height="411" alt="Image" src="https://github.com/user-attachments/assets/48e9e348-689e-4b2b-8390-8e7d9aceeda7" />

**Comment by 2kg0mez** [comment]
<img width="1051" height="913" alt="Image" src="https://github.com/user-attachments/assets/55b090e1-0d91-4fc6-bbc8-2fced31d2df5" /> 


<img width="502" height="655" alt="Image" src="https://github.com/user-attachments/assets/ba15614c-f67b-47ca-a5b3-78ad2587eb08" />

Esse problema não foi corrigido  na versão 1.5.2, ja reeinstalei o modpack e nada funciona! Bem estranho

**Comment by jiggak** [comment]
The first comment in this issue #8597 helped me solve this bug. Deleting the `kubejs` and `datapack` folder, then re-downloading/re-installing the pack fixed it.

**Comment by wildfirev** [comment]
I'm in version 1.6.1 and have tried the kubejs and datapack thing and I am still having this issue. I cannot make magnetic coils because the recipes looks like the pictures above, the steel shows up be everything else looks like barrier block, you shall not pass items. Any help fixing this would be great as it's preventing any progression with Oritech and the pyramid.
