### ISSUE TITLE
Issue with draconium chest

### ISSUE THREAD

**Issue by WayneFellows** [FTBTeam/FTB-Modpack-Issues#9379]
### Modpack

FTB StoneBlock 4

### Modpack version

1.0.1

### Launcher

FTB App

### Describe the bug

<img width="2559" height="1434" alt="Image" src="https://github.com/user-attachments/assets/011c3310-f2aa-4ffb-affe-53dabd2dd440" />

The texture doesnt seem to be loading 

### Steps to reproduce

Place chest no texture

### Expected behaviour

Should show texture

### Has the pack been modified

Please select an option...

**Comment by DinnerBeef** [comment]
Draconic Evolution is using its own sharders, so it breaks when using them. There is a fix, however. If you go into the config folder and edit the `iris.properties` file you can change the `allowUnknownShaders` setting to `true` and that should fix it.

**Comment by abhishekdrolia1-alt** [comment]
This didn't work, mine iris.properties already had allowunknownshaders as true but i still cant view them.
